/*
 * Selling Partner API for Catalog Items
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, see the [Catalog Items API Use Case Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/catalog-items-api-use-case-guide/catalog-items-api-use-case-guide_2020-12-01.md).
 *
 * OpenAPI spec version: 2020-12-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.shuaidd.aspi.model.catalog.v20201201;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/**
 * An item in the Amazon catalog.
 */

public class Item {
  @SerializedName("asin")
  private String asin = null;

  @SerializedName("attributes")
  private ItemAttributes attributes = null;

  @SerializedName("identifiers")
  private ItemIdentifiers identifiers = null;

  @SerializedName("images")
  private ItemImages images = null;

  @SerializedName("productTypes")
  private ItemProductTypes productTypes = null;

  @SerializedName("salesRanks")
  private ItemSalesRanks salesRanks = null;

  @SerializedName("summaries")
  private ItemSummaries summaries = null;

  @SerializedName("variations")
  private ItemVariations variations = null;

  @SerializedName("vendorDetails")
  private ItemVendorDetails vendorDetails = null;

  public Item asin(String asin) {
    this.asin = asin;
    return this;
  }

   /**
   * Get asin
   * @return asin
  **/

  public String getAsin() {
    return asin;
  }

  public void setAsin(String asin) {
    this.asin = asin;
  }

  public Item attributes(ItemAttributes attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/

  public ItemAttributes getAttributes() {
    return attributes;
  }

  public void setAttributes(ItemAttributes attributes) {
    this.attributes = attributes;
  }

  public Item identifiers(ItemIdentifiers identifiers) {
    this.identifiers = identifiers;
    return this;
  }

   /**
   * Get identifiers
   * @return identifiers
  **/

  public ItemIdentifiers getIdentifiers() {
    return identifiers;
  }

  public void setIdentifiers(ItemIdentifiers identifiers) {
    this.identifiers = identifiers;
  }

  public Item images(ItemImages images) {
    this.images = images;
    return this;
  }

   /**
   * Get images
   * @return images
  **/

  public ItemImages getImages() {
    return images;
  }

  public void setImages(ItemImages images) {
    this.images = images;
  }

  public Item productTypes(ItemProductTypes productTypes) {
    this.productTypes = productTypes;
    return this;
  }

   /**
   * Get productTypes
   * @return productTypes
  **/

  public ItemProductTypes getProductTypes() {
    return productTypes;
  }

  public void setProductTypes(ItemProductTypes productTypes) {
    this.productTypes = productTypes;
  }

  public Item salesRanks(ItemSalesRanks salesRanks) {
    this.salesRanks = salesRanks;
    return this;
  }

   /**
   * Get salesRanks
   * @return salesRanks
  **/

  public ItemSalesRanks getSalesRanks() {
    return salesRanks;
  }

  public void setSalesRanks(ItemSalesRanks salesRanks) {
    this.salesRanks = salesRanks;
  }

  public Item summaries(ItemSummaries summaries) {
    this.summaries = summaries;
    return this;
  }

   /**
   * Get summaries
   * @return summaries
  **/

  public ItemSummaries getSummaries() {
    return summaries;
  }

  public void setSummaries(ItemSummaries summaries) {
    this.summaries = summaries;
  }

  public Item variations(ItemVariations variations) {
    this.variations = variations;
    return this;
  }

   /**
   * Get variations
   * @return variations
  **/

  public ItemVariations getVariations() {
    return variations;
  }

  public void setVariations(ItemVariations variations) {
    this.variations = variations;
  }

  public Item vendorDetails(ItemVendorDetails vendorDetails) {
    this.vendorDetails = vendorDetails;
    return this;
  }

   /**
   * Get vendorDetails
   * @return vendorDetails
  **/

  public ItemVendorDetails getVendorDetails() {
    return vendorDetails;
  }

  public void setVendorDetails(ItemVendorDetails vendorDetails) {
    this.vendorDetails = vendorDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Item item = (Item) o;
    return Objects.equals(this.asin, item.asin) &&
        Objects.equals(this.attributes, item.attributes) &&
        Objects.equals(this.identifiers, item.identifiers) &&
        Objects.equals(this.images, item.images) &&
        Objects.equals(this.productTypes, item.productTypes) &&
        Objects.equals(this.salesRanks, item.salesRanks) &&
        Objects.equals(this.summaries, item.summaries) &&
        Objects.equals(this.variations, item.variations) &&
        Objects.equals(this.vendorDetails, item.vendorDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(asin, attributes, identifiers, images, productTypes, salesRanks, summaries, variations, vendorDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Item {\n");

    sb.append("    asin: ").append(toIndentedString(asin)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    identifiers: ").append(toIndentedString(identifiers)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    productTypes: ").append(toIndentedString(productTypes)).append("\n");
    sb.append("    salesRanks: ").append(toIndentedString(salesRanks)).append("\n");
    sb.append("    summaries: ").append(toIndentedString(summaries)).append("\n");
    sb.append("    variations: ").append(toIndentedString(variations)).append("\n");
    sb.append("    vendorDetails: ").append(toIndentedString(vendorDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

