/*
 * Selling Partner API for Reports
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * OpenAPI spec version: 2020-09-04
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.shuaidd.aspi.model.report;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/**
 * CreateReportScheduleResult
 */
public class CreateReportScheduleResult {
  @SerializedName("reportScheduleId")
  private String reportScheduleId = null;

  public CreateReportScheduleResult reportScheduleId(String reportScheduleId) {
    this.reportScheduleId = reportScheduleId;
    return this;
  }

  /**
   * The identifier for the report schedule. This identifier is unique only in combination with a seller ID.
   *
   * @return reportScheduleId
   **/

  public String getReportScheduleId() {
    return reportScheduleId;
  }

  public void setReportScheduleId(String reportScheduleId) {
    this.reportScheduleId = reportScheduleId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateReportScheduleResult createReportScheduleResult = (CreateReportScheduleResult) o;
    return Objects.equals(this.reportScheduleId, createReportScheduleResult.reportScheduleId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reportScheduleId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateReportScheduleResult {\n");

    sb.append("    reportScheduleId: ").append(toIndentedString(reportScheduleId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

