/*
 * Selling Partner API for Feeds
 * The Selling Partner API for Feeds lets you upload data to Amazon on behalf of a selling partner.
 *
 * OpenAPI spec version: 2020-09-04
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.shuaidd.aspi.model.feed;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * Information required to encrypt and upload a feed document&#39;s contents.
 */
public class CreateFeedDocumentResult {
  @SerializedName("feedDocumentId")
  private String feedDocumentId = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("encryptionDetails")
  private FeedDocumentEncryptionDetails encryptionDetails = null;

  public CreateFeedDocumentResult feedDocumentId(String feedDocumentId) {
    this.feedDocumentId = feedDocumentId;
    return this;
  }

   /**
   * The identifier of the feed document.
   * @return feedDocumentId
  **/

  public String getFeedDocumentId() {
    return feedDocumentId;
  }

  public void setFeedDocumentId(String feedDocumentId) {
    this.feedDocumentId = feedDocumentId;
  }

  public CreateFeedDocumentResult url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The presigned URL for uploading the feed contents. This URL expires after 5 minutes.
   * @return url
  **/

  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public CreateFeedDocumentResult encryptionDetails(FeedDocumentEncryptionDetails encryptionDetails) {
    this.encryptionDetails = encryptionDetails;
    return this;
  }

   /**
   * Get encryptionDetails
   * @return encryptionDetails
  **/

  public FeedDocumentEncryptionDetails getEncryptionDetails() {
    return encryptionDetails;
  }

  public void setEncryptionDetails(FeedDocumentEncryptionDetails encryptionDetails) {
    this.encryptionDetails = encryptionDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateFeedDocumentResult createFeedDocumentResult = (CreateFeedDocumentResult) o;
    return Objects.equals(this.feedDocumentId, createFeedDocumentResult.feedDocumentId) &&
        Objects.equals(this.url, createFeedDocumentResult.url) &&
        Objects.equals(this.encryptionDetails, createFeedDocumentResult.encryptionDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feedDocumentId, url, encryptionDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateFeedDocumentResult {\n");

    sb.append("    feedDocumentId: ").append(toIndentedString(feedDocumentId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    encryptionDetails: ").append(toIndentedString(encryptionDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

