/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.shuaidd.aspi.model.order;

import com.google.gson.annotations.SerializedName;



import java.util.Objects;

/**
 * Buyer information for custom orders from the Amazon Custom program.
 */

public class BuyerCustomizedInfoDetail {
  @SerializedName("CustomizedURL")
  private String customizedURL = null;

  public BuyerCustomizedInfoDetail customizedURL(String customizedURL) {
    this.customizedURL = customizedURL;
    return this;
  }

   /**
   * The location of a zip file containing Amazon Custom data.
   * @return customizedURL
  **/

  public String getCustomizedURL() {
    return customizedURL;
  }

  public void setCustomizedURL(String customizedURL) {
    this.customizedURL = customizedURL;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuyerCustomizedInfoDetail buyerCustomizedInfoDetail = (BuyerCustomizedInfoDetail) o;
    return Objects.equals(this.customizedURL, buyerCustomizedInfoDetail.customizedURL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customizedURL);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuyerCustomizedInfoDetail {\n");

    sb.append("    customizedURL: ").append(toIndentedString(customizedURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

