/*
 * Selling Partner API for Services
 * With the Services API, you can build applications that help service providers get and modify their service orders.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.shuaidd.aspi.model.service;

import com.google.gson.annotations.SerializedName;
import com.github.shuaidd.aspi.model.common.ErrorList;
import com.github.shuaidd.aspi.model.common.ErrorList;

import java.util.Objects;

/**
 * Response schema for GetJobs operation.
 */

public class GetServiceJobsResponse {
  @SerializedName("payload")
  private JobListing payload = null;

  @SerializedName("errors")
  private ErrorList errors = null;

  public GetServiceJobsResponse payload(JobListing payload) {
    this.payload = payload;
    return this;
  }

   /**
   * The payload for the GetJobs operation.
   * @return payload
  **/

  public JobListing getPayload() {
    return payload;
  }

  public void setPayload(JobListing payload) {
    this.payload = payload;
  }

  public GetServiceJobsResponse errors(ErrorList errors) {
    this.errors = errors;
    return this;
  }

   /**
   * An unexpected condition occurred during the GetServiceJobs operation.
   * @return errors
  **/

  public ErrorList getErrors() {
    return errors;
  }

  public void setErrors(ErrorList errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetServiceJobsResponse getServiceJobsResponse = (GetServiceJobsResponse) o;
    return Objects.equals(this.payload, getServiceJobsResponse.payload) &&
        Objects.equals(this.errors, getServiceJobsResponse.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payload, errors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetServiceJobsResponse {\n");

    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

