/*
 * Selling Partner API for Catalog Items
 * The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.shuaidd.aspi.model.catalog;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * ListMatchingItemsResponse
 */

public class ListMatchingItemsResponse {
  @SerializedName("Items")
  private ItemList items = null;

  public ListMatchingItemsResponse items(ItemList items) {
    this.items = items;
    return this;
  }

   /**
   * Get items
   * @return items
  **/

  public ItemList getItems() {
    return items;
  }

  public void setItems(ItemList items) {
    this.items = items;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListMatchingItemsResponse listMatchingItemsResponse = (ListMatchingItemsResponse) o;
    return Objects.equals(this.items, listMatchingItemsResponse.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListMatchingItemsResponse {\n");

    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

