/*
 * Selling Partner API for Product Fees
 * The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.shuaidd.aspi.model.product.fee;

import com.google.gson.annotations.SerializedName;



import java.util.Objects;

/**
 * Response schema.
 */

public class GetMyFeesEstimateResult {
  @SerializedName("FeesEstimateResult")
  private FeesEstimateResult feesEstimateResult = null;

  public GetMyFeesEstimateResult feesEstimateResult(FeesEstimateResult feesEstimateResult) {
    this.feesEstimateResult = feesEstimateResult;
    return this;
  }

   /**
   * The item&#39;s estimated fees.
   * @return feesEstimateResult
  **/

  public FeesEstimateResult getFeesEstimateResult() {
    return feesEstimateResult;
  }

  public void setFeesEstimateResult(FeesEstimateResult feesEstimateResult) {
    this.feesEstimateResult = feesEstimateResult;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMyFeesEstimateResult getMyFeesEstimateResult = (GetMyFeesEstimateResult) o;
    return Objects.equals(this.feesEstimateResult, getMyFeesEstimateResult.feesEstimateResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feesEstimateResult);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMyFeesEstimateResult {\n");

    sb.append("    feesEstimateResult: ").append(toIndentedString(feesEstimateResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

