/*
 * Selling Partner API for Fulfillment Inbound
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.shuaidd.aspi.model.fulfillment.inbound;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/**
 * The fees for Amazon to prep goods for shipment.
 */

public class AmazonPrepFeesDetails {
  @SerializedName("PrepInstruction")
  private PrepInstruction prepInstruction = null;

  @SerializedName("FeePerUnit")
  private Amount feePerUnit = null;

  public AmazonPrepFeesDetails prepInstruction(PrepInstruction prepInstruction) {
    this.prepInstruction = prepInstruction;
    return this;
  }

   /**
   * Get prepInstruction
   * @return prepInstruction
  **/

  public PrepInstruction getPrepInstruction() {
    return prepInstruction;
  }

  public void setPrepInstruction(PrepInstruction prepInstruction) {
    this.prepInstruction = prepInstruction;
  }

  public AmazonPrepFeesDetails feePerUnit(Amount feePerUnit) {
    this.feePerUnit = feePerUnit;
    return this;
  }

   /**
   * The fee for Amazon to prepare 1 unit.
   * @return feePerUnit
  **/

  public Amount getFeePerUnit() {
    return feePerUnit;
  }

  public void setFeePerUnit(Amount feePerUnit) {
    this.feePerUnit = feePerUnit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AmazonPrepFeesDetails amazonPrepFeesDetails = (AmazonPrepFeesDetails) o;
    return Objects.equals(this.prepInstruction, amazonPrepFeesDetails.prepInstruction) &&
        Objects.equals(this.feePerUnit, amazonPrepFeesDetails.feePerUnit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prepInstruction, feePerUnit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AmazonPrepFeesDetails {\n");

    sb.append("    prepInstruction: ").append(toIndentedString(prepInstruction)).append("\n");
    sb.append("    feePerUnit: ").append(toIndentedString(feePerUnit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

